apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: paascloud-kafka1
  name: paascloud-kafka1
  namespace: saas
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: paascloud-kafka1
  template:
    metadata:
      labels:
        app: paascloud-kafka1
    spec:
      containers:
        - env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: 'paascloud-provider-zk1:2181'
            - name: KAFKA_LISTENERS
              value: 'INSIDE://:9092,OUTSIDE://:9094'
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: INSIDE
            - name: KAFKA_ADVERTISED_LISTENERS
              value: 'INSIDE://paascloud-kafka1:9092,OUTSIDE://:9094'
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: 'INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT'
          image: 'registry.cn-shanghai.aliyuncs.com/zhachaoy/kafka:1.0.0'
          imagePullPolicy: IfNotPresent
          name: paascloud-kafka1
          ports:
            - containerPort: 9092
              protocol: TCP
            - containerPort: 9094
              protocol: TCP

      dnsPolicy: ClusterFirst

      restartPolicy: Always
      
---
apiVersion: v1
kind: Service
metadata:
  name: paascloud-kafka1
#  namespace: zhanghong
spec:
  ports:
  - port: 9092
  selector:
    app: paascloud-kafka1
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: paascloud-provider-zk1
  name: paascloud-provider-zk1
  namespace: saas
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: paascloud-provider-zk1
  template:
    metadata:
      labels:
        app: paascloud-provider-zk1
    spec:
      containers:
      - name: paascloud-provider-zk1
        imagePullPolicy: Always
        image: "registry-vpc.cn-shanghai.aliyuncs.com/iotbull-aliyun/kubernetes-zookeeper:1.0-3.4.12"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        command:
        - sh
        - -c
        - "start-zookeeper \
          --servers=3 \
          --data_dir=/var/lib/zookeeper/data \
          --data_log_dir=/var/lib/zookeeper/data/log \
          --conf_dir=/opt/zookeeper/conf \
          --client_port=2181 \
          --election_port=3888 \
          --server_port=2888 \
          --tick_time=2000 \
          --init_limit=10 \
          --sync_limit=5 \
          --heap=512M \
          --max_client_cnxns=60 \
          --snap_retain_count=3 \
          --purge_interval=12 \
          --max_session_timeout=40000 \
          --min_session_timeout=4000 \
          --log_level=INFO"         
      dnsPolicy: ClusterFirst
      restartPolicy: Always    
---
apiVersion: v1
kind: Service
metadata:
  name: paascloud-provider-zk1
#  namespace: zhanghong
spec:
  ports:
  - port: 2181
  selector:
    app: paascloud-provider-zk1   
