apiVersion: apps/v1
kind: Deployment
metadata:
  name: paascloud-db-mysql2
#  namespace: zhanghong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paascloud-db-mysql2
  template:
    metadata:
      labels:
        app: paascloud-db-mysql2
    spec:
#      nodeSelector:
#        paascloud_kafka: default     
      nodeName: okd-node-5

      containers:
      - name: paascloud-db-mysql2
        image:  mysql:5.7
        imagePullPolicy: Always
        resources:
          requests:
            memory: "2Gi"
            cpu: "2"
          limits:
            memory: "2Gi"
            cpu: "2"        
        ports:
        - containerPort: 3306
          name: server     
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: paascloud_uac
        - name: MYSQL_USER
          value: iotbull
        - name: MYSQL_PASSWORD
          value: iotbull123          
        volumeMounts:
        - name: configmap
          mountPath: /etc/mysql/conf.d/mysqld.cnf  
          subPath: path/to/mysqld.cnf    
        - name: paascloud-db-mysql2
          mountPath: /var/lib/mysql  
        securityContext:
          privileged: true     #挂本地磁盘时给权限         
      volumes:
      - name: configmap
        configMap:
          name: mysql-config 
          items:
          - key: mysqld.cnf
            path: path/to/mysqld.cnf
#      - name: paascloud-db-mysql2
#        persistentVolumeClaim:
#          claimName: paascloud-db-mysql2
      - name: paascloud-db-mysql2
        hostPath:
          path: /mysqlData1
#          type: 'Directory'
#      initContainers:
#      - name: chmod-perm-mysql
#        image: busybox     
#        command: ['sh' ,'-c', 'chmod 777 -R /tmp']
#        volumeMounts:
#        - name: paascloud-db-mysql2
#          mountPath: /tmp
   

                  
---
kind: Service
apiVersion: v1
metadata:
  name: paascloud-db-mysql2
#  namespace: zhanghong
spec:
  selector:
    app: paascloud-db-mysql2
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  externalIPs:
    - 192.168.10.132
    
---

  
        


          